import { Inter } from "next/font/google"
import "./globals.css"
import { Providers } from "./provider"
import ProviderStore from "@/store/ProviderStore"
const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Dash board",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${inter.className}`}>
          <ProviderStore>{children}</ProviderStore>
        </body>
      </Providers>
    </html>
  )
}
