import { Inter } from "next/font/google"
import "./globals.css"
import { Providers } from "./provider"
import ProviderStore from "@/store/ProviderStore"
import AuthProvider from "@/components/AuthProvider"
import { Toaster } from "react-hot-toast"
const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Dash board",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <Providers>
          <body className={`${inter.className}`}>
            <ProviderStore>{children}</ProviderStore>
          </body>
        </Providers>
      </AuthProvider>
      <Toaster />
    </html>
  )
}
