import TableUsers from "./TableUsers"

const api = process.env.NEXT_PUBLIC_API
export const metadata = {
  title: "Users | Dash board",
  description: "Generated by create next app",
}

async function Users() {
  return (
    <div className="flex-1 p-4 ">
      <h2 className="mb-2 text-3xl font-bold text-center text-gray-700">
        Danh sách Users
      </h2>
      <TableUsers />
    </div>
  )
}

export default Users
