import { checkUser } from "@/utils/checkUser"
import { Button } from "@nextui-org/react"
import Link from "next/link"
import { redirect } from "next/navigation"
import { FcGoogle } from "react-icons/fc"
import { FaGithub } from "react-icons/fa"
const api = process.env.NEXT_PUBLIC_API
export const metadata = {
  title: "SignIn | Dashboard",
  description: "Generated by create next app",
}
async function SignIn() {
  const infoUser = await checkUser()
  if (infoUser?.id) {
    return redirect("/")
  }
  return (
    <div className="flex gap-4 items-center justify-center h-[100vh]">
      <Button variant="bordered" color="primary" radius="sm" className="p-6">
        <Link href={`${api}/auth/google`} className="flex items-center gap-1">
          <span className="text-xl">Login with Google</span>{" "}
          <FcGoogle fontSize={"1.6rem"} />
        </Link>
      </Button>
      <Button
        variant="bordered"
        color="default"
        radius="sm"
        className="p-6 border-black"
      >
        <Link href={`${api}/auth/github`} className="flex items-center gap-1">
          <span className="text-xl">Login with Github</span>{" "}
          <FaGithub fontSize={"1.6rem"} />
        </Link>
      </Button>
    </div>
  )
}

export default SignIn
