-- Tạo database
CREATE DATABASE database_02_daithe;

---------- customers --------------
CREATE TABLE "customers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "phone" varchar(15),
  "email" varchar(50),
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

----------- products -----------
CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "price" float NOT NULL,
  "quantity" integer NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

----------- orders -----------
CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" boolean DEFAULT (true),
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);
 
 ------------- order detail -------------
CREATE TABLE "order_detail" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "product_id" integer,
  "order_id" integer,
  "name_product" varchar(50),
  "name_user" varchar(50),
  "price" float NOT NULL,
  "amount" integer NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

ALTER TABLE "order_detail" ADD FOREIGN KEY ("user_id") REFERENCES "customers" ("id");

ALTER TABLE "order_detail" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "order_detail" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

---------- insert customers ----------
INSERT INTO customers (name, phone, email)
VALUES
  ('John Doe', '123456789', 'john.doe@example.com'),
  ('Alice Johnson', '987654321', 'alice.johnson@example.com'),
  ('Bob Smith', '555123456', 'bob.smith@example.com'),
  ('Charlie Brown', '777888999', 'charlie.brown@example.com');
 
 -------- insert products --------
INSERT INTO products (name, price, quantity) VALUES
  ('Product A', 19.99, 100),
  ('Product B', 29.99, 50),
  ('Product B', 39.99, 80);

---------- insert orders ----------
INSERT INTO orders (status) VALUES
  (true),
  (false);
---------- insert order_detail ----------
INSERT INTO order_detail (user_id, product_id, order_id, name_product, name_user, price, amount) VALUES
  (13, 1, 1, 'Product A', 'John Doe', 19.99, 2);
INSERT INTO order_detail (user_id, product_id, order_id, name_product, name_user, price, amount) VALUES
  (14, 2, 2, 'Product B', 'Alice Johnson', 29.99, 1);
  
--------- Xem danh sách đơn hàng ---------
SELECT
  customers.name AS "Tên khách hàng",
  customers.email AS "Email khách hàng",
  customers.phone AS "Số điện thoại khách hàng",
  SUM(order_detail.amount) AS "Tổng số lượng sản phẩm",
  SUM(order_detail.amount * order_detail.price) AS "Tổng tiền đơn hàng",
  orders.status AS "Trạng thái đơn hàng",
  orders.created_at AS "Thời gian đặt hàng"
FROM
  customers
JOIN
  order_detail ON customers.id = order_detail.user_id
JOIN
  orders ON order_detail.order_id = orders.id
GROUP BY
  customers.id, orders.id;
 
 --------- Xem chi tiết đơn hàng ---------
 SELECT
  customers.name AS "Tên khách hàng",
  customers.email AS "Email khách hàng",
  customers.phone AS "Số điện thoại khách hàng",
  products.name AS "Tên sản phẩm",
  products.id AS "Mã sản phẩm",
  order_detail.price AS "Giá",
  order_detail.amount AS "Số lượng",
  order_detail.amount * order_detail.price AS "Tổng tiền từng sản phẩm",
  orders.status AS "Trạng thái đơn hàng",
  orders.created_at AS "Thời gian tạo đơn hàng",
  orders.updated_at AS "Thời gian cập nhật cuối cùng"
FROM
  customers
JOIN
  order_detail ON customers.id = order_detail.user_id
JOIN
  orders ON order_detail.order_id = orders.id
JOIN
  products ON order_detail.product_id = products.id;



